name: Scheduled Execution of process.py

on:
  schedule:
    - cron: '10 4 * * *'  # Expected execution time
    - cron: '00 5 * * *'  # Backup time

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        env:
          NORDOMAIN_30DAY_URL: ${{ secrets.NORDOMAIN_30DAY_URL }}
          NORDOMAIN_14DAY_URL: ${{ secrets.NORDOMAIN_14DAY_URL }}
          PHISHING_30DAY_URL: ${{ secrets.PHISHING_30DAY_URL }}
          PHISHING_14DAY_URL: ${{ secrets.PHISHING_14DAY_URL }}
        run: python src/process.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update NRD Lists"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
