name: Scheduled Script Execution

on:
  schedule:
    - cron: '00 5 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          python3.13 -m pip install --upgrade pip
          python3.13 -m pip install requests

      - name: Create Temp Directory
        run: mkdir -p temp

      - name: Run script
        env:
          NORDOMAIN_30DAY_URL: ${{ secrets.NORDOMAIN_30DAY_URL }}
          NORDOMAIN_14DAY_URL: ${{ secrets.NORDOMAIN_14DAY_URL }}
          PHISHING_30DAY_URL: ${{ secrets.PHISHING_30DAY_URL }}
          PHISHING_14DAY_URL: ${{ secrets.PHISHING_14DAY_URL }}
        run: |
          python3.13 src/nrd-hunter.py || echo "Script failed, investigate logs"

      - name: Validate Output Files
        run: |
          if [ -z "$(ls -A output/)" ]; then
            echo "No output files found in output/ directory"
            exit 1
          fi
        shell: bash

      - name: Move output files
        run: |
          mkdir -p lists/14-day lists/30-day lists/14-day_phishing lists/30-day_phishing
          for file in output/*; do
            if [ -f "$file" ]; then
              case "$file" in
                *14day.txt) mv "$file" lists/14-day/domains-only/ ;;
                *30day.txt) mv "$file" lists/30-day/domains-only/ ;;
                # Add more cases here as needed for other file types
              esac
            else
              echo "Skipping non-file $file"
            fi
          done
        shell: bash

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add lists/ || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update NRD Lists ($(date +'%Y-%m-%d'))"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}